- name: install apache and php last version
  apt:
    name:
      - apache2
      - php
      - php-mysql
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags:
    - install
